#!/usr/bin/env node
/**
 * Generate the legal policy manifest + AR/EN inventory doc from the shared
 * canonical legal JSON. Mirrors scripts/generateStoreCatalog.js.
 *
 *   node scripts/generateLegalManifest.js          # write artifacts
 *   node scripts/generateLegalManifest.js --check  # CI drift gate (exit 1 on drift)
 *
 * Source of truth: shared/src/legal/documents/*.json (read via
 * src/shared/legal/legalContent.js). All content is owner-gated
 * (ownerApproval: BLOCKED_NEEDS_OWNER) until counsel signs off.
 */

const fs = require("fs");
const path = require("path");
const { buildLegalManifest } = require("../src/shared/legal/legalManifest");

const repoRoot = path.resolve(__dirname, "..", "..");
const JSON_PATH = path.resolve(__dirname, "..", "src", "shared", "legal", "legalPolicies.generated.json");
const DOCS_DIR = path.resolve(repoRoot, "docs", "evidence", "store-readiness", "generated");
const MD_PATH = path.join(DOCS_DIR, "legal-policy-manifest.generated.md");

function renderInventory(manifest) {
  const lines = [];
  lines.push("# Legal policy manifest (generated)\n");
  lines.push(
    "GENERATED by `labbe-backend-/scripts/generateLegalManifest.js` from " +
      "`shared/src/legal/documents/*.json`. Do not edit by hand — run " +
      "`npm run legal:generate` and commit.\n"
  );
  lines.push(`- Manifest version: \`${manifest.manifestVersion}\``);
  lines.push(`- Origin: \`${manifest.origin}\``);
  lines.push(`- Documents: **${manifest.documentCount}**`);
  lines.push(`- UGC-required: ${manifest.ugcRequiredDocuments.map((d) => `\`${d}\``).join(", ")}`);
  lines.push(`- Manifest hash: \`${manifest.manifestHash}\`\n`);
  lines.push("| documentType | version | approved | AR URL | EN URL | sections |");
  lines.push("|---|---|---|---|---|---|");
  for (const d of manifest.documents) {
    lines.push(
      `| ${d.documentType} | ${d.version} | ${d.approved ? "yes" : "**NO (BLOCKED_NEEDS_OWNER)**"} | ${d.urls.ar} | ${d.urls.en} | ${d.sectionIds.length} |`
    );
  }
  lines.push("");
  lines.push(
    "> Every document is `ownerApproval: BLOCKED_NEEDS_OWNER`. Counsel/owner must " +
      "sign the exact copy, entity/contact data, retention periods, and " +
      "refund/subscription wording before any document is treated as approved.\n"
  );
  return lines.join("\n");
}

function buildArtifacts() {
  const manifest = buildLegalManifest(); // validates or throws
  return [
    { path: JSON_PATH, content: JSON.stringify(manifest, null, 2) + "\n" },
    { path: MD_PATH, content: renderInventory(manifest) },
  ];
}

// Normalize CRLF→LF so a git autocrlf checkout never triggers a false drift.
const norm = (s) => s.replace(/\r\n/g, "\n");

function findDrift() {
  const drifted = [];
  for (const { path: p, content } of buildArtifacts()) {
    let current = null;
    try {
      current = fs.readFileSync(p, "utf8");
    } catch {
      current = null;
    }
    if (current === null || norm(current) !== norm(content)) {
      drifted.push(path.relative(repoRoot, p));
    }
  }
  return drifted;
}

function main() {
  const check = process.argv.includes("--check");
  const artifacts = buildArtifacts();

  if (check) {
    const drifted = findDrift();
    if (drifted.length) {
      console.error(
        `\n✗ legal-manifest drift: ${drifted.length} generated artifact(s) differ from source.\n` +
          drifted.map((d) => `   - ${d}`).join("\n") +
          `\n\nRun \`npm run legal:generate\` and commit the result.\n`
      );
      process.exit(1);
    }
    console.log(`✓ legal manifest in sync — ${artifacts.length} artifacts match source (no drift).`);
    return;
  }

  fs.mkdirSync(DOCS_DIR, { recursive: true });
  for (const { path: p, content } of artifacts) {
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, content);
    console.log(`  wrote ${path.relative(repoRoot, p)}`);
  }
  console.log(`\n✓ generated ${artifacts.length} legal artifacts.`);
}

if (require.main === module) main();

module.exports = { buildArtifacts, findDrift, norm, JSON_PATH, MD_PATH };
