"use client";
import { useState, useCallback, useMemo, useEffect } from "react";
import { useForm } from "react-hook-form";
import { useRouter, usePathname } from "next/navigation";
import { useTranslation } from "react-i18next";
import { toastUtils } from "@/utils/toastUtils";

// Constants
const DEFAULT_ADDRESS = {
  address: "",
  latitude: 24.7136,
  longitude: 46.6753,
  city: "",
  country: "",
};

const DEFAULT_FORM_VALUES = {
  // Step 1 - Event Details
  eventType: "",
  eventName: "",
  eventDate: "",
  eventTime: "12:00:AM",
  address: DEFAULT_ADDRESS,
  // Step 2 - Guests and Staff
  guestList: [],
  staffList: [],
  // Step 3 - Visual invitation card (generated by TemplateForm)
  templateImage: "",
  visualTemplate: null,     // { id, name, src, data: { brideName, groomName, ... } }
  // Step 4 - Taqnyat template + auto-replies
  selectedTemplate: null,   // { id, name, bodyText } from Taqnyat
  attendanceAutoReply: "",
  absenceAutoReply: "",
  expectedAttendanceAutoReply: "",
  note: "",
  // Step 5 - Schedule and confirmation (create only)
  sendSchedule: "now",
  scheduleDate: "",
  scheduleTime: "",
  confirmReviewed: false,
};

// Data transformation utilities
export const transformGuestList = (guests = []) =>
  guests.map((guest) => ({
    id: guest._id || guest.id || Date.now() + Math.random(),
    name: guest.name || "",
    mobile: guest.phone || "",
    email: guest.email || "",
  }));

export const transformStaffList = (staff = []) =>
  staff.map((s) => ({
    id: s._id || s.id || Date.now() + Math.random(),
    name: s.name || "",
    mobile: s.phone || "",
  }));

export const mapEventToFormValues = (event) => ({
  eventType: event.eventDetails?.type || "",
  eventName: event.eventDetails?.title || "",
  eventDate: event.eventDetails?.date || "",
  eventTime: event.eventDetails?.time || "12:00:AM",
  address: event.eventDetails?.location || DEFAULT_ADDRESS,
  guestList: transformGuestList(event.guestList),
  staffList: transformStaffList(event.staffList),
  templateImage: event.invitationSettings?.templateImage || "",
  visualTemplate: event.invitationSettings?.visualTemplate || null,
  selectedTemplate: event.invitationSettings?.selectedTemplate || null,
  attendanceAutoReply: event.invitationSettings?.attendanceAutoReply || "",
  absenceAutoReply: event.invitationSettings?.absenceAutoReply || "",
  expectedAttendanceAutoReply:
    event.invitationSettings?.expectedAttendanceAutoReply || "",
  note: event.invitationSettings?.note || "",
  sendSchedule: "now",
  scheduleDate: "",
  scheduleTime: "",
  confirmReviewed: false,
});

export const buildEventPayload = (data) => ({
  eventDetails: {
    title: data.eventName,
    type: data.eventType,
    date: data.eventDate,
    time: data.eventTime,
    location: data.address,
  },
  guestList: (data.guestList || []).map((guest) => ({
    name: guest.name,
    phone: guest.mobile || guest.phone,
    email: guest.email || "",
  })),
  staffList: (data.staffList || []).map((s) => ({
    name: s.name,
    phone: s.mobile || s.phone,
  })),
  invitationSettings: {
    // selectedTemplate.name is the Taqnyat templateName used when sending
    selectedTemplate: data.selectedTemplate
      ? {
          id: data.selectedTemplate.id,
          name: data.selectedTemplate.name,
          bodyText: data.selectedTemplate.bodyText,
          image: data.selectedTemplate.image,
          hasImageHeader: data.selectedTemplate.hasImageHeader ?? false,
        }
      : undefined,
    // visualTemplate stores the Step 3 card design data
    visualTemplate: data.visualTemplate || undefined,
    attendanceAutoReply: data.attendanceAutoReply,
    absenceAutoReply: data.absenceAutoReply,
    expectedAttendanceAutoReply: data.expectedAttendanceAutoReply,
    templateImage: data.templateImage,
    note: data.note,
  },
  launchSettings: {
    sendSchedule: data.sendSchedule || "now",
    scheduledDate: data.scheduleDate,
    scheduledTime: data.scheduleTime,
  },
});

/**
 * Unified hook for event form management
 * Handles both create and update modes with shared validation and state logic
 */
export const useEventForm = (options = {}) => {
  const {
    mode = "create", // 'create' | 'update'
    eventId = null,
    initialData = null,
    totalSteps = 5,
    onSuccess = null,
  } = options;

  const router = useRouter();
  const pathname = usePathname();
  const locale = pathname.split("/")[1];
  const { t } = useTranslation("createEvent");

  const [currentStep, setCurrentStep] = useState(1);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const methods = useForm({
    mode: "onChange",
    defaultValues: DEFAULT_FORM_VALUES,
  });

  const { watch, reset, setValue, handleSubmit } = methods;
  const formData = watch();

  // Reset form when initial data changes (for update mode)
  useEffect(() => {
    if (initialData && mode === "update") {
      reset(mapEventToFormValues(initialData));
    }
  }, [initialData, mode, reset]);

  // Step validation
  const validateStep = useCallback(
    (step) => {
      switch (step) {
        case 1:
          return (
            formData.eventType &&
            formData.eventName &&
            formData.eventDate &&
            formData.eventTime
          );
        case 2:
          return formData.guestList && formData.guestList.length > 0;
        case 3:
          return !!(formData.templateImage) || !!(formData.visualTemplate?.id);
        case 4:
          return !!(formData.selectedTemplate?.name);
        case 5:
          return formData.confirmReviewed === true;
        default:
          return false;
      }
    },
    [formData]
  );

  const isStepValid = useMemo(
    () => validateStep(currentStep),
    [validateStep, currentStep]
  );

  // Navigation
  const goToStep = useCallback(
    (step) => {
      if (step >= 1 && step <= totalSteps) {
        setCurrentStep(step);
      }
    },
    [totalSteps]
  );

  const goToNextStep = useCallback(() => {
    if (!validateStep(currentStep)) {
      toastUtils.error(t("errors.complete_required_fields"));
      return false;
    }
    if (currentStep < totalSteps) {
      setCurrentStep((prev) => prev + 1);
      return true;
    }
    return false;
  }, [currentStep, totalSteps, validateStep, t]);

  const goToPreviousStep = useCallback(() => {
    if (currentStep > 1) {
      setCurrentStep((prev) => prev - 1);
      return true;
    }
    return false;
  }, [currentStep]);

  // Staff management
  const watchedStaffList = watch("staffList");
  const staffList = useMemo(
    () => watchedStaffList || [],
    [watchedStaffList]
  );

  const addStaffMember = useCallback(
    (staffMember) => {
      setValue("staffList", [...staffList, staffMember], {
        shouldValidate: true,
      });
    },
    [staffList, setValue]
  );

  const editStaffMember = useCallback(
    (updatedMember) => {
      const updatedList = staffList.map((item) =>
        item.id === updatedMember.id ? updatedMember : item
      );
      setValue("staffList", updatedList, { shouldValidate: true });
    },
    [staffList, setValue]
  );

  const deleteStaffMember = useCallback(
    (id) => {
      const updatedList = staffList.filter((item) => item.id !== id);
      setValue("staffList", updatedList, { shouldValidate: true });
    },
    [staffList, setValue]
  );

  // Build update payload based on step (for update mode)
  const buildStepPayload = useCallback(
    (step) => {
      switch (step) {
        case 1:
          return {
            type: "eventDetails",
            data: {
              title: formData.eventName,
              type: formData.eventType,
              date: formData.eventDate,
              time: formData.eventTime,
              location: formData.address,
              description: "",
            },
            successMessage: t("success.event_details_updated"),
          };
        case 2:
          return {
            type: "guestList",
            data: {
              guestList: (formData.guestList || []).map((guest) => ({
                name: guest.name,
                phone: guest.mobile || guest.phone || "",
                email: guest.email || "",
              })),
              staffList: (formData.staffList || []).map((s) => ({
                name: s.name,
                phone: s.mobile || s.phone || "",
              })),
            },
            successMessage: t("success.guest_list_updated"),
          };
        case 3:
          return {
            type: "invitationSettings",
            data: {
              visualTemplate: formData.visualTemplate || undefined,
              ...(formData.templateImage instanceof File && {
                templateImage: formData.templateImage,
              }),
            },
            successMessage: t("success.invitation_settings_updated"),
          };
        case 4:
          return {
            type: "invitationSettings",
            data: {
              selectedTemplate: formData.selectedTemplate
                ? {
                    ...formData.selectedTemplate,
                    hasImageHeader: formData.selectedTemplate.hasImageHeader ?? false,
                  }
                : formData.selectedTemplate,
              attendanceAutoReply: formData.attendanceAutoReply,
              absenceAutoReply: formData.absenceAutoReply,
              expectedAttendanceAutoReply: formData.expectedAttendanceAutoReply,
              note: formData.note,
            },
            successMessage: t("success.message_customization_updated"),
          };
        default:
          return null;
      }
    },
    [formData, t]
  );

  // Cancel/back to host page
  const cancel = useCallback(() => {
    router.push(`/${locale}/host`);
  }, [router, locale]);

  return {
    // Form methods
    methods,
    formData,
    reset,
    setValue,
    handleSubmit,
    // Step management
    currentStep,
    totalSteps,
    goToStep,
    goToNextStep,
    goToPreviousStep,
    isStepValid,
    validateStep,
    // Submission state
    isSubmitting,
    setIsSubmitting,
    // Staff
    staffList,
    addStaffMember,
    editStaffMember,
    deleteStaffMember,
    // Utilities
    locale,
    cancel,
    buildStepPayload,
    buildEventPayload: () => buildEventPayload(formData),
    // Mode info
    mode,
    eventId,
    t,
  };
};

export default useEventForm;
