"use client";
import { useState, useCallback, useMemo, useEffect } from "react";
import { useForm } from "react-hook-form";
import { useRouter, usePathname } from "next/navigation";
import { useTranslation } from "react-i18next";
import { toastUtils } from "@/utils/toastUtils";

// Constants
const DEFAULT_ADDRESS = {
  address: "",
  latitude: 24.7136,
  longitude: 46.6753,
  city: "",
  country: "",
};

const DEFAULT_FORM_VALUES = {
  // Step 1 - Event Details
  eventType: "",
  eventName: "",
  eventDate: "",
  eventTime: "12:00:AM",
  address: DEFAULT_ADDRESS,
  // Step 2 - Guests and Staff
  guestList: [],
  staffList: [],
  // Step 3 - Visual invitation card (generated by TemplateForm)
  templateImage: "",
  visualTemplate: null,     // { id, name, src, data: { brideName, groomName, ... } }
  // Step 4 - Taqnyat template + auto-replies
  selectedTemplate: null,   // { id, name, bodyText } from Taqnyat
  attendanceAutoReply: "",
  absenceAutoReply: "",
  expectedAttendanceAutoReply: "",
  note: "",
  // Step 5 - Schedule and confirmation (create only)
  sendSchedule: "now",
  scheduleDate: "",
  scheduleTime: "",
  confirmReviewed: false,
};

// Data transformation utilities
export const transformGuestList = (guests = []) =>
  guests.map((guest) => ({
    id: guest._id || guest.id || Date.now() + Math.random(),
    name: guest.name || "",
    mobile: guest.phone || "",
    email: guest.email || "",
  }));

export const transformStaffList = (staff = []) =>
  staff.map((s) => ({
    id: s._id || s.id || Date.now() + Math.random(),
    name: s.name || "",
    mobile: s.phone || "",
  }));

export const mapEventToFormValues = (event) => ({
  eventType: event.eventDetails?.type || "",
  eventName: event.eventDetails?.title || "",
  eventDate: event.eventDetails?.date || "",
  eventTime: event.eventDetails?.time || "12:00:AM",
  address: event.eventDetails?.location || DEFAULT_ADDRESS,
  guestList: transformGuestList(event.guestList),
  staffList: transformStaffList(event.staffList),
  // Phase 4c W1-WIZARD-RENAME — read from canonical fields first (new
  // backend reads), fall back to legacy `invitationSettings.*` for
  // pre-migration events during the dual-write window.
  templateImage:
    event.visualTemplate?.bakedImagePath ||
    event.invitationSettings?.templateImage ||
    "",
  visualTemplate:
    event.visualTemplate?.templateRef
      ? {
          ...(event.invitationSettings?.visualTemplate || {}),
          templateRef: event.visualTemplate.templateRef,
          fieldValues: event.visualTemplate.fieldValues,
          bakedImagePath: event.visualTemplate.bakedImagePath,
          // legacy mirrors so existing consumers still work
          id: event.visualTemplate.templateRef,
          data: event.visualTemplate.fieldValues,
          src: event.visualTemplate.bakedImagePath,
        }
      : event.invitationSettings?.visualTemplate || null,
  selectedTemplate: event.invitationSettings?.selectedTemplate || null,
  taqnyatTemplate: event.taqnyatTemplate || null,
  attendanceAutoReply:
    event.guestReplies?.onAttend ||
    event.invitationSettings?.attendanceAutoReply ||
    "",
  absenceAutoReply:
    event.guestReplies?.onAbsent ||
    event.invitationSettings?.absenceAutoReply ||
    "",
  expectedAttendanceAutoReply:
    event.guestReplies?.onExpected ||
    event.invitationSettings?.expectedAttendanceAutoReply ||
    "",
  guestReplies: event.guestReplies || {
    onAttend: event.invitationSettings?.attendanceAutoReply || "",
    onAbsent: event.invitationSettings?.absenceAutoReply || "",
    onExpected: event.invitationSettings?.expectedAttendanceAutoReply || "",
  },
  invitationMessage: event.invitationMessage || "",
  hostNote: event.hostNote || event.invitationSettings?.note || "",
  note: event.invitationSettings?.note || event.hostNote || "",
  sendSchedule: "now",
  scheduleDate: "",
  scheduleTime: "",
  confirmReviewed: false,
});

export const buildEventPayload = (data) => ({
  eventDetails: {
    title: data.eventName,
    type: data.eventType,
    date: data.eventDate,
    time: data.eventTime,
    location: data.address,
  },
  guestList: (data.guestList || []).map((guest) => ({
    name: guest.name,
    phone: guest.mobile || guest.phone,
    email: guest.email || "",
  })),
  staffList: (data.staffList || []).map((s) => ({
    name: s.name,
    phone: s.mobile || s.phone,
  })),
  // Phase 4c W1-WIZARD-RENAME — DUAL-WRITE both shapes:
  // legacy `invitationSettings.*` for existing consumers + canonical
  // top-level fields per W0-RENAME for new reads.
  invitationSettings: {
    // selectedTemplate.name is the Taqnyat templateName used when sending
    selectedTemplate: data.selectedTemplate
      ? {
          id: data.selectedTemplate.id,
          name: data.selectedTemplate.name,
          bodyText: data.selectedTemplate.bodyText,
          image: data.selectedTemplate.image,
          hasImageHeader: data.selectedTemplate.hasImageHeader ?? false,
        }
      : undefined,
    // visualTemplate stores the Step 3 card design data
    visualTemplate: data.visualTemplate || undefined,
    attendanceAutoReply:
      data.guestReplies?.onAttend || data.attendanceAutoReply,
    absenceAutoReply:
      data.guestReplies?.onAbsent || data.absenceAutoReply,
    expectedAttendanceAutoReply:
      data.guestReplies?.onExpected || data.expectedAttendanceAutoReply,
    templateImage: data.templateImage,
    note: data.hostNote || data.note,
  },
  // Canonical top-level keys per Phase 4c W0-RENAME — backend dual-write
  // accepts these alongside `invitationSettings.*`.
  taqnyatTemplateRef:
    data.taqnyatTemplate?.templateRef ||
    data.taqnyatTemplateRef ||
    data.selectedTemplate?._id ||
    data.selectedTemplate?.id,
  fieldValues:
    data.visualTemplate?.fieldValues || data.visualTemplate?.data,
  visualTemplateRef:
    data.visualTemplate?.templateRef ||
    data.visualTemplate?._id ||
    data.visualTemplate?.id,
  guestReplies: data.guestReplies || {
    onAttend: data.attendanceAutoReply,
    onAbsent: data.absenceAutoReply,
    onExpected: data.expectedAttendanceAutoReply,
  },
  invitationMessage: data.invitationMessage,
  hostNote: data.hostNote || data.note,
  launchSettings: {
    sendSchedule: data.sendSchedule || "now",
    scheduledDate: data.scheduleDate,
    scheduledTime: data.scheduleTime,
  },
});

/**
 * Unified hook for event form management
 * Handles both create and update modes with shared validation and state logic
 */
export const useEventForm = (options = {}) => {
  const {
    mode = "create", // 'create' | 'update'
    eventId = null,
    initialData = null,
    totalSteps = 5,
    onSuccess = null,
  } = options;

  const router = useRouter();
  const pathname = usePathname();
  const locale = pathname.split("/")[1];
  const { t } = useTranslation("createEvent");

  const [currentStep, setCurrentStep] = useState(1);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const methods = useForm({
    mode: "onChange",
    defaultValues: DEFAULT_FORM_VALUES,
  });

  const { watch, reset, setValue, handleSubmit } = methods;
  const formData = watch();

  // Reset form when initial data changes (for update mode)
  useEffect(() => {
    if (initialData && mode === "update") {
      reset(mapEventToFormValues(initialData));
    }
  }, [initialData, mode, reset]);

  // Step validation — Phase 4c W1-WIZARD-RENAME locked the 6-step
  // structure (D4c-1):
  //   1 details / 2 guest+staff / 3 visual template / 4 Taqnyat
  //   picker / 5 messaging+replies+note / 6 summary
  const validateStep = useCallback(
    (step) => {
      switch (step) {
        case 1:
          return (
            formData.eventType &&
            formData.eventName &&
            formData.eventDate &&
            formData.eventTime
          );
        case 2:
          return formData.guestList && formData.guestList.length > 0;
        case 3:
          // Visual template: either a backend template was picked
          // (visualTemplate.templateRef / .id) OR the legacy
          // hardcoded template image is set.
          return (
            !!formData.templateImage ||
            !!formData.visualTemplate?.templateRef ||
            !!formData.visualTemplate?.id ||
            !!formData.visualTemplate?._id
          );
        case 4:
          // Taqnyat template picker: legacy `selectedTemplate.name`
          // or canonical `taqnyatTemplate.templateRef`.
          return (
            !!formData.selectedTemplate?.name ||
            !!formData.taqnyatTemplate?.templateRef ||
            !!formData.taqnyatTemplateRef
          );
        case 5:
          // Messaging + replies + note. The default replies are seeded
          // by StepFive on mount, so this is satisfied as soon as the
          // host sees the step.
          return true;
        case 6:
          return formData.confirmReviewed === true;
        default:
          return false;
      }
    },
    [formData]
  );

  const isStepValid = useMemo(
    () => validateStep(currentStep),
    [validateStep, currentStep]
  );

  // Navigation
  const goToStep = useCallback(
    (step) => {
      if (step >= 1 && step <= totalSteps) {
        setCurrentStep(step);
      }
    },
    [totalSteps]
  );

  const goToNextStep = useCallback(() => {
    if (!validateStep(currentStep)) {
      toastUtils.error(t("errors.complete_required_fields"));
      return false;
    }
    if (currentStep < totalSteps) {
      setCurrentStep((prev) => prev + 1);
      return true;
    }
    return false;
  }, [currentStep, totalSteps, validateStep, t]);

  const goToPreviousStep = useCallback(() => {
    if (currentStep > 1) {
      setCurrentStep((prev) => prev - 1);
      return true;
    }
    return false;
  }, [currentStep]);

  // Staff management
  const watchedStaffList = watch("staffList");
  const staffList = useMemo(
    () => watchedStaffList || [],
    [watchedStaffList]
  );

  const addStaffMember = useCallback(
    (staffMember) => {
      setValue("staffList", [...staffList, staffMember], {
        shouldValidate: true,
      });
    },
    [staffList, setValue]
  );

  const editStaffMember = useCallback(
    (updatedMember) => {
      const updatedList = staffList.map((item) =>
        item.id === updatedMember.id ? updatedMember : item
      );
      setValue("staffList", updatedList, { shouldValidate: true });
    },
    [staffList, setValue]
  );

  const deleteStaffMember = useCallback(
    (id) => {
      const updatedList = staffList.filter((item) => item.id !== id);
      setValue("staffList", updatedList, { shouldValidate: true });
    },
    [staffList, setValue]
  );

  // Build update payload based on step (for update mode)
  const buildStepPayload = useCallback(
    (step) => {
      switch (step) {
        case 1:
          return {
            type: "eventDetails",
            data: {
              title: formData.eventName,
              type: formData.eventType,
              date: formData.eventDate,
              time: formData.eventTime,
              location: formData.address,
              description: "",
            },
            successMessage: t("success.event_details_updated"),
          };
        case 2:
          return {
            type: "guestList",
            data: {
              guestList: (formData.guestList || []).map((guest) => ({
                name: guest.name,
                phone: guest.mobile || guest.phone || "",
                email: guest.email || "",
              })),
              staffList: (formData.staffList || []).map((s) => ({
                name: s.name,
                phone: s.mobile || s.phone || "",
              })),
            },
            successMessage: t("success.guest_list_updated"),
          };
        case 3:
          return {
            type: "invitationSettings",
            data: {
              visualTemplate: formData.visualTemplate || undefined,
              ...(formData.templateImage instanceof File && {
                templateImage: formData.templateImage,
              }),
            },
            successMessage: t("success.invitation_settings_updated"),
          };
        case 4:
          // Phase 4c W1-WIZARD-RENAME — Step 4 is the Taqnyat picker
          // only. Auto-replies + note moved to Step 5.
          return {
            type: "invitationSettings",
            data: {
              selectedTemplate: formData.selectedTemplate
                ? {
                    ...formData.selectedTemplate,
                    hasImageHeader: formData.selectedTemplate.hasImageHeader ?? false,
                  }
                : formData.selectedTemplate,
              // Canonical key — backend dual-write reads either.
              taqnyatTemplateRef:
                formData.taqnyatTemplate?.templateRef ||
                formData.taqnyatTemplateRef ||
                formData.selectedTemplate?._id ||
                formData.selectedTemplate?.id,
            },
            successMessage: t("success.template_selected"),
          };
        case 5:
          // Phase 4c W1-WIZARD-RENAME — Step 5 carries messaging +
          // replies + note. Dual-writes legacy `attendanceAutoReply` /
          // `absenceAutoReply` / `expectedAttendanceAutoReply` / `note`
          // alongside canonical `guestReplies.*` / `invitationMessage` /
          // `hostNote`.
          return {
            type: "invitationSettings",
            data: {
              attendanceAutoReply:
                formData.guestReplies?.onAttend || formData.attendanceAutoReply,
              absenceAutoReply:
                formData.guestReplies?.onAbsent || formData.absenceAutoReply,
              expectedAttendanceAutoReply:
                formData.guestReplies?.onExpected || formData.expectedAttendanceAutoReply,
              note: formData.hostNote || formData.note,
              guestReplies: formData.guestReplies,
              invitationMessage: formData.invitationMessage,
              hostNote: formData.hostNote || formData.note,
            },
            successMessage: t("success.message_customization_updated"),
          };
        default:
          return null;
      }
    },
    [formData, t]
  );

  // Cancel/back to host page
  const cancel = useCallback(() => {
    router.push(`/${locale}/host`);
  }, [router, locale]);

  return {
    // Form methods
    methods,
    formData,
    reset,
    setValue,
    handleSubmit,
    // Step management
    currentStep,
    totalSteps,
    goToStep,
    goToNextStep,
    goToPreviousStep,
    isStepValid,
    validateStep,
    // Submission state
    isSubmitting,
    setIsSubmitting,
    // Staff
    staffList,
    addStaffMember,
    editStaffMember,
    deleteStaffMember,
    // Utilities
    locale,
    cancel,
    buildStepPayload,
    buildEventPayload: () => buildEventPayload(formData),
    // Mode info
    mode,
    eventId,
    t,
  };
};

export default useEventForm;
