"use client";
import { useState, useCallback, useMemo, useEffect } from "react";
import { useForm } from "react-hook-form";
import { useRouter, usePathname } from "next/navigation";
import { useTranslation } from "react-i18next";
import { toastUtils } from "@/utils/toastUtils";
import { DEFAULT_INVITATION_TYPE } from "@/utils/invitationTypes";

// Constants
const DEFAULT_ADDRESS = {
  address: "",
  latitude: 24.7136,
  longitude: 46.6753,
  city: "",
  country: "",
};

const DEFAULT_FORM_VALUES = {
  // Step 1 - Event Details
  eventType: "",
  eventName: "",
  eventDate: "",
  eventTime: "12:00:AM",
  address: DEFAULT_ADDRESS,
  // Step 2 - Guests and Staff
  guestList: [],
  staffList: [],
  // Step 3 - Visual invitation card (generated by TemplateForm)
  templateImage: "",
  visualTemplate: { isCustomUpload: true, fieldValues: {} },
  // Step 4 - Taqnyat template + auto-replies
  selectedTemplate: null,
  taqnyatTemplate: null,
  invitationType: DEFAULT_INVITATION_TYPE,
  guestReplies: {
    onAttend: "",
    onAbsent: "",
  },
  // Step 5 - Schedule and confirmation (create only)
  sendSchedule: "now",
  scheduleDate: "",
  scheduleTime: "",
  confirmReviewed: false,
};

// Data transformation utilities
export const transformGuestList = (guests = []) =>
  guests.map((guest) => ({
    id: guest._id || guest.id || Date.now() + Math.random(),
    name: guest.name || "",
    mobile: guest.phone || "",
    category: guest.category || "",
  }));

export const transformStaffList = (staff = []) =>
  staff.map((s) => ({
    id: s._id || s.id || Date.now() + Math.random(),
    name: s.name || "",
    mobile: s.phone || "",
  }));

// `event.visualTemplate.templateRef` and `event.taqnyatTemplate.templateRef`
// are populated by the backend (events.crud.service findById path) so the
// step-3 picker / step-4 picker can highlight the saved selection and
// preview body text without a follow-up fetch.
//
// Custom-upload events: the doc has `isCustomUpload: true`, no
// templateRef, and the uploaded image URL on `bakedImagePath`. We carry
// the flag through so StepThree opens in upload mode and the host sees
// the previously uploaded card.
const populatedVisualTemplate = (event) => {
  const vt = event.visualTemplate;
  if (!vt) return { isCustomUpload: true, fieldValues: {} };
  if (vt.isCustomUpload) {
    return {
      isCustomUpload: true,
      fieldValues: {},
      bakedImagePath: vt.bakedImagePath || null,
    };
  }
  const ref = vt.templateRef;
  if (!ref) return null;
  // Populated docs are objects with _id; raw ObjectId strings are bare
  // strings. Both shapes carry the canonical templateRef forward.
  if (typeof ref === "object" && ref !== null) {
    return {
      ...ref,
      templateRef: ref._id,
      fieldValues: vt.fieldValues || {},
      bakedImagePath: vt.bakedImagePath || null,
      isCustomUpload: false,
    };
  }
  return {
    templateRef: ref,
    fieldValues: vt.fieldValues || {},
    bakedImagePath: vt.bakedImagePath || null,
    isCustomUpload: false,
  };
};

const populatedSelectedTemplate = (event) => {
  const ref = event.taqnyatTemplate?.templateRef;
  if (!ref) return null;
  if (typeof ref === "object" && ref !== null) {
    return {
      _id: ref._id,
      id: ref._id,
      name: ref.templateName || ref.name,
      templateName: ref.templateName,
      bodyText: ref.bodyText,
      hasImageHeader: ref.hasImageHeader || false,
      language: ref.language || "ar",
    };
  }
  return { _id: ref, id: ref };
};

export const mapEventToFormValues = (event) => ({
  eventType: event.eventDetails?.type || "",
  eventName: event.eventDetails?.title || "",
  eventDate: event.eventDetails?.date || "",
  eventTime: event.eventDetails?.time || "12:00:AM",
  address: event.eventDetails?.location || DEFAULT_ADDRESS,
  guestList: transformGuestList(event.guestList),
  staffList: transformStaffList(event.staffList),
  templateImage:
    event.visualTemplate?.bakedImagePath || event.templateImage || "",
  visualTemplate: populatedVisualTemplate(event),
  selectedTemplate: populatedSelectedTemplate(event),
  taqnyatTemplate: event.taqnyatTemplate || null,
  invitationType: event.invitationType || DEFAULT_INVITATION_TYPE,
  guestReplies: {
    onAttend: event.guestReplies?.onAttend || "",
    onAbsent: event.guestReplies?.onAbsent || "",
  },
  sendSchedule: "now",
  scheduleDate: "",
  scheduleTime: "",
  confirmReviewed: false,
});

export const buildEventPayload = (data = {}) => ({
  eventDetails: {
    title: data.eventName,
    type: data.eventType,
    date: data.eventDate,
    time: data.eventTime,
    location: data.address,
  },
  guestList: (data.guestList || []).map((guest) => ({
    name: guest.name,
    phone: guest.mobile || guest.phone,
    ...(guest.category ? { category: guest.category } : {}),
  })),
  staffList: (data.staffList || []).map((s) => ({
    name: s.name,
    phone: s.mobile || s.phone,
  })),
  // Canonical top-level keys (no legacy invitationSettings mirror).
  visualTemplate: data.visualTemplate
    ? data.visualTemplate.isCustomUpload
      ? {
          isCustomUpload: true,
          fieldValues: {},
        }
      : {
          templateRef:
            data.visualTemplate.templateRef ||
            data.visualTemplate._id ||
            data.visualTemplate.id,
          fieldValues:
            data.visualTemplate.fieldValues || data.visualTemplate.data || {},
          isCustomUpload: false,
        }
    : undefined,
  taqnyatTemplate: data.selectedTemplate
    ? {
        templateRef:
          data.taqnyatTemplate?.templateRef ||
          data.selectedTemplate._id ||
          data.selectedTemplate.id,
      }
    : undefined,
  guestReplies: {
    onAttend: data.guestReplies?.onAttend || "",
    onAbsent: data.guestReplies?.onAbsent || "",
  },
  invitationType: data.invitationType || DEFAULT_INVITATION_TYPE,
  templateImage: data.templateImage,
  launchSettings: {
    sendSchedule: data.sendSchedule || "now",
    scheduledDate: data.scheduleDate,
    scheduledTime: data.scheduleTime,
  },
});

import { validateEventStep } from "./eventFormValidation.js";
export { validateEventStep };

/**
 * Unified hook for event form management
 * Handles both create and update modes with shared validation and state logic
 */
export const useEventForm = (options = {}) => {
  const {
    mode = "create", // 'create' | 'update'
    eventId = null,
    initialData = null,
    totalSteps = 5,
    onSuccess = null,
  } = options;

  const router = useRouter();
  const pathname = usePathname();
  const locale = pathname.split("/")[1];
  const { t } = useTranslation("createEvent");

  const [currentStep, setCurrentStep] = useState(1);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const methods = useForm({
    mode: "onChange",
    defaultValues: DEFAULT_FORM_VALUES,
  });

  const { watch, reset, setValue, handleSubmit } = methods;
  const formData = watch();

  // Reset form when initial data changes (for update mode)
  useEffect(() => {
    if (initialData && mode === "update") {
      reset(mapEventToFormValues(initialData));
    }
  }, [initialData, mode, reset]);

  // Step validation — 5-step wizard
  const validateStep = useCallback(
    (step) => validateEventStep(step, formData),
    [formData]
  );

  const isStepValid = useMemo(
    () => validateStep(currentStep),
    [validateStep, currentStep]
  );

  // Navigation
  const goToStep = useCallback(
    (step) => {
      if (step >= 1 && step <= totalSteps) {
        setCurrentStep(step);
      }
    },
    [totalSteps]
  );

  const goToNextStep = useCallback(() => {
    if (!validateStep(currentStep)) {
      toastUtils.error(t("errors.complete_required_fields"));
      return false;
    }
    if (currentStep < totalSteps) {
      setCurrentStep((prev) => prev + 1);
      return true;
    }
    return false;
  }, [currentStep, totalSteps, validateStep, t]);

  const goToPreviousStep = useCallback(() => {
    if (currentStep > 1) {
      setCurrentStep((prev) => prev - 1);
      return true;
    }
    return false;
  }, [currentStep]);

  // Staff management
  const watchedStaffList = watch("staffList");
  const staffList = useMemo(
    () => watchedStaffList || [],
    [watchedStaffList]
  );

  const addStaffMember = useCallback(
    (staffMember) => {
      setValue("staffList", [...staffList, staffMember], {
        shouldValidate: true,
      });
    },
    [staffList, setValue]
  );

  const editStaffMember = useCallback(
    (updatedMember) => {
      const updatedList = staffList.map((item) =>
        item.id === updatedMember.id ? updatedMember : item
      );
      setValue("staffList", updatedList, { shouldValidate: true });
    },
    [staffList, setValue]
  );

  const deleteStaffMember = useCallback(
    (id) => {
      const updatedList = staffList.filter((item) => item.id !== id);
      setValue("staffList", updatedList, { shouldValidate: true });
    },
    [staffList, setValue]
  );

  // Build update payload based on step (for update mode)
  const buildStepPayload = useCallback(
    (step) => {
      switch (step) {
        case 1:
          return {
            type: "eventDetails",
            data: {
              title: formData.eventName,
              type: formData.eventType,
              date: formData.eventDate,
              time: formData.eventTime,
              location: formData.address,
              description: formData.description,
            },
          };
        case 2:
          return {
            type: "guestList",
            data: {
              guestList: (formData.guestList || []).map((guest) => ({
                name: guest.name,
                phone: guest.mobile || guest.phone,
                ...(guest.category ? { category: guest.category } : {}),
              })),
              staffList: (formData.staffList || []).map((s) => ({
                name: s.name,
                phone: s.mobile || s.phone,
              })),
            },
          };
        case 3:
          return {
            type: "visualTemplate",
            data: formData.visualTemplate
              ? formData.visualTemplate.isCustomUpload
                ? {
                    isCustomUpload: true,
                    fieldValues: {},
                  }
                : {
                    templateRef:
                      formData.visualTemplate.templateRef ||
                      formData.visualTemplate._id ||
                      formData.visualTemplate.id,
                    fieldValues:
                      formData.visualTemplate.fieldValues ||
                      formData.visualTemplate.data ||
                      {},
                    isCustomUpload: false,
                  }
              : undefined,
            templateImage: formData.templateImage,
          };
        case 4:
          return {
            type: "invitationSettings",
            data: {
              taqnyatTemplate: formData.selectedTemplate
                ? {
                    templateRef:
                      formData.taqnyatTemplate?.templateRef ||
                      formData.selectedTemplate._id ||
                      formData.selectedTemplate.id,
                  }
                : undefined,
              guestReplies: {
                onAttend: formData.guestReplies?.onAttend || "",
                onAbsent: formData.guestReplies?.onAbsent || "",
              },
              invitationType:
                formData.invitationType || DEFAULT_INVITATION_TYPE,
            },
          };
        default:
          return null;
      }
    },
    [formData]
  );

  // Cancel/back to host page
  const cancel = useCallback(() => {
    router.push(`/${locale}/host`);
  }, [router, locale]);

  return {
    methods,
    formData,
    currentStep,
    totalSteps,
    isSubmitting,
    setIsSubmitting,
    goToStep,
    goToNextStep,
    goToPreviousStep,
    isStepValid,
    validateStep,
    staffList,
    addStaffMember,
    editStaffMember,
    deleteStaffMember,
    buildStepPayload,
    locale,
    cancel,
    t,
    reset,
    setValue,
    handleSubmit,
    buildEventPayload: () => buildEventPayload(formData),
    mode,
    eventId,
  };
};

export default useEventForm;
